#pragma once
// Generated by tools/generate_settings_schema.py.
inline constexpr char settingsSchema[] = R"json({
  "account.bilibili.sourceEnabled": {
    "category": "accounts",
    "default": false
  },
  "app.launchAtLogin": {
    "category": "general",
    "default": false
  },
  "appearance.albumLayout": {
    "category": "appearance",
    "default": "Flow",
    "values": [
      "Flow",
      "Grid",
      "Mosaic"
    ]
  },
  "appearance.dynamicArtworkEnabled": {
    "category": "appearance",
    "default": true
  },
  "appearance.mode": {
    "category": "other",
    "default": "System",
    "values": [
      "System",
      "Light",
      "Dark"
    ]
  },
  "audio.outputDeviceId": {
    "category": "playback",
    "default": "default",
    "values": [
      "default"
    ]
  },
  "audio.pauseOnDeviceRemoval": {
    "category": "playback",
    "default": true
  },
  "background.autoBlurPx": {
    "category": "appearance",
    "default": 32,
    "max": 192,
    "min": 0
  },
  "background.blur": {
    "category": "appearance",
    "default": 56,
    "max": 192,
    "min": 0
  },
  "background.color": {
    "category": "appearance",
    "default": "#c8bad9"
  },
  "background.image": {
    "category": "appearance",
    "default": "",
    "path": true
  },
  "background.mask": {
    "category": "appearance",
    "default": 0.0,
    "max": 100.0,
    "min": 0.0
  },
  "background.type": {
    "category": "appearance",
    "default": "AutoCover",
    "values": [
      "AutoCover",
      "Image",
      "Color",
      "Video",
      "Wallpaper"
    ]
  },
  "background.video": {
    "category": "appearance",
    "default": "",
    "path": true
  },
  "background.wallpaper": {
    "category": "appearance",
    "default": "",
    "path": true
  },
  "background.wallpaperFolder": {
    "category": "appearance",
    "default": "",
    "path": true
  },
  "download.embedContent.Album": {
    "category": "download",
    "default": false
  },
  "download.embedContent.Artist": {
    "category": "download",
    "default": true
  },
  "download.embedContent.Artwork": {
    "category": "download",
    "default": true
  },
  "download.embedContent.Lyrics": {
    "category": "download",
    "default": true
  },
  "download.enabled": {
    "category": "download",
    "default": true
  },
  "download.existingFilePolicy": {
    "category": "download",
    "default": "Skip",
    "values": [
      "Skip",
      "AutoRename",
      "Overwrite"
    ]
  },
  "download.fileNameTemplate": {
    "category": "download",
    "default": "TitleArtist",
    "values": [
      "TitleArtist",
      "ArtistTitle",
      "TitleOnly"
    ]
  },
  "download.folder": {
    "category": "download",
    "default": "",
    "path": true
  },
  "download.lyrics.content.Original": {
    "category": "download",
    "default": true
  },
  "download.lyrics.content.Romanization": {
    "category": "download",
    "default": false
  },
  "download.lyrics.content.Translation": {
    "category": "download",
    "default": true
  },
  "download.lyrics.content.WordTiming": {
    "category": "download",
    "default": false
  },
  "download.lyrics.encoding": {
    "category": "download",
    "default": "Utf8",
    "values": [
      "Utf8",
      "Gbk"
    ]
  },
  "download.lyrics.externalFile": {
    "category": "download",
    "default": false
  },
  "download.maxConcurrent": {
    "category": "download",
    "default": 1,
    "values": [
      1,
      2,
      3,
      4,
      5,
      6
    ]
  },
  "download.tryAlternateSource": {
    "category": "download",
    "default": true
  },
  "immersive.background": {
    "category": "appearance",
    "default": "aura",
    "values": [
      "aura",
      "blur",
      "mv"
    ]
  },
  "immersive.hideDelay": {
    "category": "appearance",
    "default": 3
  },
  "immersive.lyricStyle": {
    "category": "appearance",
    "default": "fume",
    "values": [
      "fume",
      "classic",
      "cadenza",
      "partita",
      "cappella",
      "tilt",
      "claddagh",
      "diorama",
      "monet",
      "pendolo",
      "sonnet",
      "tempera",
      "still"
    ]
  },
  "immersive.visualHeight": {
    "category": "appearance",
    "default": 112
  },
  "immersive.visualization": {
    "category": "appearance",
    "default": "none",
    "values": [
      "none",
      "spectrum",
      "ambient"
    ]
  },
  "library.autoWatch": {
    "category": "library",
    "default": true
  },
  "list.rememberScrollPosition": {
    "category": "other",
    "default": true
  },
  "lyrics.alignment": {
    "category": "appearance",
    "default": "Center",
    "values": [
      "Left",
      "Center",
      "Right"
    ]
  },
  "lyrics.chineseConversion": {
    "category": "appearance",
    "default": "Off",
    "values": [
      "Off",
      "Simplified",
      "Traditional"
    ]
  },
  "lyrics.currentLineAnchor": {
    "category": "appearance",
    "default": "Center",
    "values": [
      "Center",
      "Upper",
      "Lower"
    ]
  },
  "lyrics.currentLineScaleEnabled": {
    "category": "appearance",
    "default": true
  },
  "lyrics.inactiveBlurEnabled": {
    "category": "appearance",
    "default": true
  },
  "lyrics.karaokeEnabled": {
    "category": "appearance",
    "default": true
  },
  "lyrics.secondaryLineOrder": {
    "category": "appearance",
    "default": "TranslationFirst",
    "values": [
      "TranslationFirst",
      "RomanizationFirst"
    ]
  },
  "lyrics.showRomanization": {
    "category": "appearance",
    "default": false
  },
  "lyrics.showTranslation": {
    "category": "appearance",
    "default": true
  },
  "lyrics.springScrollingEnabled": {
    "category": "appearance",
    "default": true
  },
  "lyrics.textSize": {
    "category": "appearance",
    "default": 28.0,
    "max": 48.0,
    "min": 16.0
  },
  "lyrics.wordTimingEnabled": {
    "category": "appearance",
    "default": true
  },
  "nowPlaying.backgroundStyle": {
    "category": "appearance",
    "default": "SolidMaterial",
    "values": [
      "SolidMaterial",
      "BlurredArtwork",
      "DynamicFlow"
    ]
  },
  "nowPlaying.playerStyle": {
    "category": "appearance",
    "default": "Classic",
    "values": [
      "Classic",
      "Overflow"
    ]
  },
  "playback.autoPlayOnLaunch": {
    "category": "playback",
    "default": false
  },
  "playback.clearShuffleHistory": {
    "category": "playback",
    "default": true
  },
  "playback.defaultMode": {
    "category": "playback",
    "default": "LoopAll",
    "values": [
      "LoopAll",
      "Shuffle",
      "LoopOne",
      "Endless",
      "StopAfterCurrent"
    ]
  },
  "playback.playActionBehavior": {
    "category": "playback",
    "default": "AppendToQueue",
    "values": [
      "AppendToQueue",
      "ReplaceCurrentList"
    ]
  },
  "playback.preventSystemSleep": {
    "category": "playback",
    "default": true
  },
  "playback.quality": {
    "category": "playback",
    "default": "flac",
    "values": [
      "flac",
      "320k",
      "128k"
    ]
  },
  "playback.restorePosition": {
    "category": "playback",
    "default": true
  },
  "playback.skipOnError": {
    "category": "playback",
    "default": true
  },
  "playback.transition.smart": {
    "category": "playback",
    "default": false
  },
  "search.focusOnLaunch": {
    "category": "other",
    "default": false
  },
  "settingsBackup.devicePathHandling": {
    "category": "backup",
    "default": "Ignore",
    "values": [
      "Ignore",
      "Create"
    ]
  },
  "settingsBackup.includeDevicePaths": {
    "category": "backup",
    "default": false
  },
  "shortcuts.application.back": {
    "category": "shortcuts",
    "default": "Esc"
  },
  "shortcuts.application.enabled": {
    "category": "shortcuts",
    "default": true
  },
  "shortcuts.application.focusSearch": {
    "category": "shortcuts",
    "default": "F1"
  },
  "shortcuts.application.next": {
    "category": "shortcuts",
    "default": "Ctrl+Right"
  },
  "shortcuts.application.playPause": {
    "category": "shortcuts",
    "default": "Ctrl+F5"
  },
  "shortcuts.application.previous": {
    "category": "shortcuts",
    "default": "Ctrl+Left"
  },
  "shortcuts.global.enabled": {
    "category": "shortcuts",
    "default": false
  },
  "shortcuts.global.next": {
    "category": "shortcuts",
    "default": "Ctrl+Alt+Right"
  },
  "shortcuts.global.playPause": {
    "category": "shortcuts",
    "default": "Ctrl+Alt+F5"
  },
  "shortcuts.global.previous": {
    "category": "shortcuts",
    "default": "Ctrl+Alt+Left"
  },
  "shortcuts.global.volumeDown": {
    "category": "shortcuts",
    "default": "Ctrl+Alt+Down"
  },
  "shortcuts.global.volumeUp": {
    "category": "shortcuts",
    "default": "Ctrl+Alt+Up"
  },
  "source.nameStyle": {
    "category": "source",
    "default": "Alias",
    "values": [
      "Original",
      "Alias"
    ]
  },
  "source.updateNotificationsEnabled": {
    "category": "source",
    "default": true
  },
  "tray.enabled": {
    "category": "other",
    "default": true
  },
  "tray.iconStyle": {
    "category": "other",
    "default": "Auto",
    "values": [
      "Auto",
      "Light",
      "Dark"
    ]
  },
  "ui.fontFamily": {
    "category": "general",
    "default": "SystemDefault"
  },
  "ui.language": {
    "category": "general",
    "default": "ZhCn",
    "values": [
      "ZhCn",
      "EnUs"
    ]
  },
  "ui.motionEnabled": {
    "category": "general",
    "default": true
  },
  "ui.motionStyle": {
    "category": "general",
    "default": "Elegant",
    "values": [
      "Elegant",
      "Bright"
    ]
  },
  "ui.refreshRateLimit": {
    "category": "general",
    "default": 60,
    "values": [
      60,
      90,
      120
    ]
  },
  "window.askBeforeClosing": {
    "category": "other",
    "default": true
  },
  "window.closeAction": {
    "category": "other",
    "default": "Quit",
    "values": [
      "Quit",
      "MinimizeToTray"
    ]
  },
  "window.showTaskbarProgress": {
    "category": "playback",
    "default": true
  },
  "window.startInFullScreen": {
    "category": "general",
    "default": false
  },
  "window.transparencyEnabled": {
    "category": "other",
    "default": true
  }
})json";
