const esbuild = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');
const output = path.resolve(__dirname, '../../src/third_party/sourcehost_browser');
fs.mkdirSync(output, {recursive: true});
esbuild.buildSync({
  entryPoints: [path.join(__dirname, 'entry.js')],
  outfile: path.join(output, 'browser.js'), bundle: true,
  platform: 'browser', format: 'iife', target: 'es2020',
  minify: true, legalComments: 'inline',
  banner: {js: '// Generated by tools/sourcehost_compat/build.cjs; see README.md and LICENSES.txt.'}
});
const packages = ['core-js', 'buffer', 'base64-js', 'ieee754'];
const licenses = packages.map(name => {
  const root = path.dirname(require.resolve(name+'/package.json'));
  const license = ['LICENSE', 'LICENSE.txt'].find(file => fs.existsSync(path.join(root,file)));
  return name+' '+require(name+'/package.json').version+'\n'+fs.readFileSync(path.join(root,license),'utf8');
}).join('\n\n');
fs.writeFileSync(path.join(output, 'LICENSES.txt'), licenses);
fs.writeFileSync(path.resolve(__dirname, '../../licenses/sourcehost-browser-MIT.txt'), licenses);
